fix: 明确 cargo workspace
由于目前此仓库通过 git 子模块放置在 os-checker 项目内，os-checker 的
workspace 与缺乏 [workspace] 的此项目发生冲突。通过在此项目添加 [workspace]，
来解决。奇怪的是，之前并没有报错。这应该是 cargo 最近更新或者修复了的某些功能导致的。

解决的错误：

Error: 无法解析 `./repos/os-checker-test-suite/` 内的 Rust 项目布局

Caused by:
    无法读取 cargo metadata 的结果：`cargo metadata` exited with an error: error: current package believes it's in a workspace when it's not:
    current:   /rust/my/os-checker/repos/os-checker-test-suite/Cargo.toml
    workspace: /rust/my/os-checker/Cargo.toml

    this may be fixable by ensuring that this crate is depended on by the workspace root: /rust/my/os-checker/Cargo.toml
    Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.